[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
      from = "/*"
      to = "https://quantum-africa.org/:splat"
      status = 301
      force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
