# -*- coding: utf-8 -*-
"""What the site lets you edit.

One declaration, three consumers: the admin panel renders its forms from it, the
API validates against it, and the site reads the keys it defines. Adding a field
is a line here — no new form code, no new endpoint.

Field types the admin understands:
    text · textarea · markdown · url · email · date · time · number
    select   (needs `options`)
    image    (upload, stored under data/media)
    list     (repeatable group, needs `fields`; `label_field` names the row)
    tags     (comma-separated list of strings)
"""
from __future__ import annotations

def F(key, label, type='text', **kw):
    f = {'key': key, 'label': label, 'type': type}
    f.update(kw)
    return f


COUNTRIES = ['Algeria', 'Egypt', 'Morocco', 'Nigeria', 'Mauritania', 'Zambia',
             'Uganda', 'South Africa', 'Tunisia', 'Kenya', 'Rwanda', 'Ghana',
             'Senegal', 'Ethiopia', 'Cameroon', 'Other']


# One picture or one video, however you have it. Used by the hero and by the
# highlight carousel, so both understand the same three shapes:
#   an uploaded image · a short uploaded clip · a link to YouTube or Vimeo
MEDIA_FIELDS = [
    F('type', 'This slide is a', 'select', options=['Photo', 'Video'],
      help='Pick Video and then fill in either an uploaded clip or a link.'),
    F('image', 'Photo', 'image',
      help='For a photo slide. Also used as the still frame for a video.'),
    F('video', 'Video file', 'image',
      help='A short clip — MP4 or WebM, under 25 MB. Good for a few seconds of '
           'atmosphere. For anything longer use a link below instead: video files '
           'live in your repository and large ones make it slow for everyone.'),
    F('videoUrl', 'Video link', 'url',
      help='A YouTube or Vimeo address. The best choice for full talks and '
           'recordings — it costs your site nothing and plays only when someone '
           'presses play.'),
    F('caption', 'Caption'),
    F('credit', 'Credit', help='Who took it, and your permission to publish it.'),
]

PERSON_FIELDS = [
    F('name', 'Full name', help='As they want it written.'),
    F('group', 'Group', 'select', options=['Leadership', 'Advisors', 'Chapter leads']),
    F('role', 'Role at Quantum Africa'),
    F('institution', 'Institution'),
    F('country', 'Country', 'select', options=COUNTRIES),
    F('photo', 'Portrait', 'image', help='Square or 4:5. At least 1200px wide.'),
    F('bio', 'Short bio', 'textarea', help='Two or three sentences. Shown on the card.'),
    F('fullBio', 'Full biography', 'markdown', help='Shown when someone opens the card. Written by them, not about them.'),
    F('interests', 'Research interests', 'tags'),
    F('chapter', 'Chapter'),
    F('linkedin', 'LinkedIn', 'url'),
    F('scholar', 'Google Scholar', 'url'),
    F('orcid', 'ORCID', 'url'),
]

SECTIONS = [
  {
    'key': 'site', 'title': 'Site basics', 'icon': 'globe', 'kind': 'single',
    'blurb': 'Names, contact details and the social accounts in the footer.',
    'fields': [
      F('name', 'Organisation name'),
      F('tagline', 'Tagline', help='One line. Appears in the footer and in search results.'),
      F('email', 'Contact email', 'email'),
      F('phone', 'Phone'),
      F('address', 'Address', 'textarea'),
      F('founded', 'Year founded'),
      F('registered', 'Registered in', help='Country of legal registration.'),
      F('linkedin', 'LinkedIn', 'url'),
      F('twitter', 'X / Twitter', 'url'),
      F('youtube', 'YouTube', 'url'),
      F('instagram', 'Instagram', 'url'),
      F('footerEmail', 'Footer email link', 'url', help='Use mailto:contact@example.com. If empty the contact email is used.'),
      F('newsletter', 'Newsletter note', 'text'),
    ],
  },
  {
    'key': 'hero', 'title': 'Homepage hero', 'icon': 'home', 'kind': 'single',
    'blurb': 'The rotating headline, the line under it, and the five images behind.',
    'fields': [
      F('eyebrow', 'Small line above the headline'),
      F('statements', 'Rotating statements', 'list', label_field='b', fields=[
        F('a', 'First half', help='Rendered in white. End it with a space.'),
        F('b', 'Second half', help='Rendered in gold.'),
        F('lede', 'Paragraph underneath', 'textarea'),
      ]),
      F('slides', 'Hero photos and videos', 'list', label_field='caption',
        fields=MEDIA_FIELDS,
        help='Landscape, 2400×1350. Videos play silently behind the headline and '
             'the slider waits for them to finish before moving on.'),
      F('ctaPrimary', 'Primary button text'),
      F('ctaSecondary', 'Secondary button text'),
    ],
  },
  {
    'key': 'stats', 'title': 'Numbers', 'icon': 'chart', 'kind': 'single',
    'blurb': 'The counters on the homepage and Impact page. Leave a field empty '
             'and the site shows nothing rather than a guess.',
    'fields': [
      F('members', 'Community members', 'number'),
      F('chapters', 'National chapters', 'number'),
      F('countries', 'Countries reached', 'number'),
      F('events', 'Events held', 'number'),
      F('projects', 'Research projects', 'number'),
      F('partners', 'Partner institutions', 'number'),
      F('note', 'How these are counted', 'textarea',
        help='Say what period each number covers. Funders read this.'),
    ],
  },
  {
    'key': 'highlight', 'title': 'Front page highlight', 'icon': 'star', 'kind': 'single',
    'blurb': 'The thing you most want people to see when they arrive — usually your '
             'latest event. Photos and videos together in one carousel.',
    'fields': [
      F('eyebrow', 'Small label above the title', help='e.g. Latest event'),
      F('title', 'Title'),
      F('date', 'Date', 'date'),
      F('place', 'Place'),
      F('summary', 'Summary', 'textarea',
        help='Two or three sentences. What happened and why it mattered.'),
      F('linkText', 'Button text', help='e.g. Read the write-up'),
      F('linkUrl', 'Button link', 'url'),
      F('gallery', 'Photos and videos', 'list', label_field='caption',
        fields=MEDIA_FIELDS,
        help='Shown as a carousel. Drag to reorder — the first one is what people '
             'see first.'),
    ],
  },
  {
    'key': 'about', 'title': 'About', 'icon': 'doc', 'kind': 'single',
    'blurb': 'Everything on the About page — hero, story, mission, vision, objectives, documents, leadership summary.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow', help='Small label above the headline, e.g. “About Quantum Africa”.'),
      F('heroTitle', 'Hero headline', help='The big sentence at the top of the page.'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('heroImage', 'Hero photograph', 'image',
        help='Wide community photograph, 2400×1000 or larger. Shows directly under the hero.'),
      F('whoWeAre', 'Who we are', 'markdown', help='Two or three short paragraphs. What Quantum Africa is, and is not.'),
      F('story', 'Our story', 'markdown'),
      F('mission', 'Mission', 'textarea'),
      F('vision', 'Vision', 'textarea'),
      F('objectives', 'Objectives', 'tags', help='One bullet per objective; rendered as the list on the About page.'),
      F('philosophyHeadline', 'Philosophy headline', help='The big line in the side panel, e.g. Educate → Research → Connect → Lead.'),
      F('philosophy', 'Philosophy note', 'textarea'),
      F('documents', 'Documents note', 'textarea',
        help='Annual report or strategy PDF — describe it and link it.'),
    ],
  },
  {
    'key': 'people', 'title': 'Team', 'icon': 'user', 'kind': 'collection',
    'blurb': 'Everyone on the Team page. Each person writes their own entry.',
    'label_field': 'name', 'fields': PERSON_FIELDS,
  },
  {
    'key': 'chapters', 'title': 'Chapters', 'icon': 'flag', 'kind': 'collection',
    'blurb': 'National chapters. The country code drives the map.',
    'label_field': 'name',
    'fields': [
      F('name', 'Country / chapter name'),
      F('code', 'Country code', help='Two letters, lowercase — dz, ma, ng. Drives the map pin.'),
      F('flag', 'Flag emoji'),
      F('status', 'Status', 'select', options=['Active', 'Launching', 'Forming', 'Paused']),
      F('lead', 'Chapter lead'),
      F('leadRole', 'Lead role / institution'),
      F('email', 'Chapter email', 'email'),
      F('description', 'About this chapter', 'markdown'),
      F('photo', 'Chapter photo', 'image', help='Team or event photo. 2400×1000.'),
      F('members', 'Members', 'number'),
      F('linkedin', 'LinkedIn', 'url'),
      F('web', 'Website', 'url'),
    ],
  },
  {
    'key': 'events', 'title': 'Our events', 'icon': 'calendar', 'kind': 'collection',
    'blurb': "Quantum Africa's own webinars, workshops and chapter events. "
             'The worldwide calendar is collected automatically and is not edited here.',
    'label_field': 'title',
    'fields': [
      F('title', 'Title'),
      F('type', 'Type', 'select', options=['Webinar', 'Workshop', 'Conference', 'Chapter event', 'Summer school']),
      F('date', 'Date', 'date'),
      F('time', 'Time', 'time', help='Include the timezone in the note below if it is not GMT.'),
      F('speaker', 'Speaker'),
      F('speakerAffil', 'Speaker affiliation'),
      F('speakerPhoto', 'Speaker photo', 'image'),
      F('abstract', 'Abstract', 'markdown'),
      F('register', 'Registration link', 'url'),
      F('recording', 'Recording link', 'url'),
      F('photo', 'Event photo', 'image'),
      F('series', 'Series', help='e.g. QML4Africa. Leave blank if it is a one-off.'),
    ],
  },
  {
    'key': 'projects', 'title': 'Research projects', 'icon': 'atom', 'kind': 'collection',
    'blurb': 'Open research projects. Anything you cannot yet evidence, leave empty.',
    'label_field': 'title',
    'fields': [
      F('title', 'Title'),
      F('area', 'Area'),
      F('short', 'One-line summary'),
      F('description', 'Description', 'markdown'),
      F('objectives', 'Objectives', 'tags', help='One per entry.'),
      F('tech', 'Tools and technologies', 'tags'),
      F('repo', 'Repository', 'url'),
      F('publication', 'Publication / DOI', 'url'),
      F('started', 'Started', 'date'),
      F('needs', 'Skills needed', 'textarea'),
      F('image', 'Project image', 'image'),
      F('contributors', 'Contributors', 'list', label_field='name', fields=[
        F('name', 'Name'), F('role', 'Role'), F('institution', 'Institution'),
      ]),
    ],
  },
  {
    'key': 'partners', 'title': 'Partners', 'icon': 'link', 'kind': 'collection',
    'blurb': 'Only organisations with a real agreement. Do not list logos you have not cleared.',
    'label_field': 'name',
    'fields': [
      F('name', 'Name'),
      F('category', 'Category', 'select',
        options=['Academic', 'Research', 'Industry', 'Education', 'Strategic']),
      F('logo', 'Logo', 'image', help='SVG or transparent PNG.'),
      F('url', 'Website', 'url'),
      F('country', 'Country'),
      F('note', 'What we do together', 'textarea'),
    ],
  },
  {
    'key': 'articles', 'title': 'News & articles', 'icon': 'news', 'kind': 'collection',
    'blurb': 'Announcements, write-ups and explainers.',
    'label_field': 'title',
    'fields': [
      F('title', 'Headline'),
      F('type', 'Type', 'select', options=['News', 'Article', 'Announcement', 'Recap']),
      F('date', 'Date', 'date'),
      F('author', 'Author'),
      F('read', 'Reading time', help='e.g. 4 min'),
      F('summary', 'Summary', 'textarea'),
      F('body', 'Body', 'markdown'),
      F('image', 'Header image', 'image'),
    ],
  },
  {
    'key': 'opportunities', 'title': 'Our opportunities', 'icon': 'star', 'kind': 'collection',
    'blurb': 'Opportunities you know about that the job boards do not carry — '
             'especially African ones. These are merged into the Opportunities page '
             'and pinned above the collected listings.',
    'label_field': 'title',
    'fields': [
      F('title', 'Title'),
      F('org', 'Institution or company'),
      F('city', 'City'),
      F('country', 'Country', 'select', options=COUNTRIES),
      F('type', 'Type', 'select',
        options=['PhD', 'Postdoc', 'MSc', 'Faculty', 'Research fellow',
                 'Internship', 'Summer school', 'Scholarship', 'Grant', 'Industry']),
      F('deadline', 'Deadline', 'date'),
      F('url', 'Application link', 'url'),
      F('note', 'Note', 'textarea'),
    ],
  },
  {
    'key': 'conference', 'title': 'Conference series', 'icon': 'award', 'kind': 'single',
    'blurb': 'Quantum Africa\'s relationship to the series, and photographs per edition. '
             'Speaker and committee lists come from the official record and are not edited here.',
    'fields': [
      F('role', "Quantum Africa's role in the series", 'markdown',
        help='Be precise: attend, co-organise, sponsor, run a satellite workshop, '
             'sit on the committee. Do not imply ownership.'),
      F('photos', 'Edition photographs', 'list', label_field='caption', fields=[
        F('edition', 'Edition', 'select',
          options=['QA1', 'QA2', 'QA3', 'QA4', 'QA5', 'QA6', 'QA7']),
        F('image', 'Photograph', 'image'),
        F('caption', 'Caption'),
        F('credit', 'Credit', help='Who took it, and your permission to publish it.'),
      ]),
      F('profiles', 'Speaker portraits and profiles', 'list', label_field='name', fields=[
        F('name', 'Name', help='Exactly as it appears in the line-up.'),
        F('photo', 'Portrait', 'image'),
        F('url', 'Profile link', 'url'),
      ]),
    ],
  },
  {
    'key': 'tutor', 'title': 'AI Tutor', 'icon': 'chat', 'kind': 'single',
    'blurb': 'The Quantum AI Tutor page.',
    'fields': [
      F('intro', 'Introduction', 'markdown'),
      F('status', 'Status', 'select', options=['In development', 'Beta', 'Live']),
      F('link', 'Link to the tutor', 'url'),
      F('screenshots', 'Screenshots', 'list', label_field='caption', fields=[
        F('image', 'Screenshot', 'image'), F('caption', 'Caption'),
      ]),
    ],
  },
  {
    'key': 'support', 'title': 'Pledge your support', 'icon': 'heart', 'kind': 'single',
    'blurb': 'Donation details and where support goes. Leave empty until it is real — '
             'the site shows a placeholder rather than an invented figure.',
    'fields': [
      F('donation', 'Donation details', 'markdown',
        help='Bank account, payment link, registered charitable status, tax position.'),
      F('splitProgrammes', 'Share to programmes (%)', 'number'),
      F('splitStudents', 'Share to student costs (%)', 'number'),
      F('splitOperations', 'Share to operations (%)', 'number'),
      F('thanks', 'Thank-you note', 'textarea'),
    ],
  },
  {
    'key': 'legal', 'title': 'Legal', 'icon': 'shield', 'kind': 'single',
    'blurb': 'Privacy, terms and code of conduct.',
    'fields': [
      F('privacy', 'Privacy policy', 'markdown'),
      F('terms', 'Terms', 'markdown'),
      F('conduct', 'Code of conduct', 'markdown'),
    ],
  },
  {
    'key': 'pages.home', 'title': 'Page: Home', 'icon': 'home', 'kind': 'single',
    'blurb': 'Static editorial copy on the homepage — pillar cards, tutor promo, sections around the collection-driven areas.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow', help='Small line above the rotating headline.'),
      F('ctaPrimary', 'Primary CTA button text', help='Left button under the hero headline.'),
      F('ctaSecondary', 'Secondary CTA button text', help='Right button under the hero headline.'),
      F('pillarEyebrow', 'Pillars section eyebrow'),
      F('pillarTitle', 'Pillars section headline'),
      F('pillarLede', 'Pillars section lede paragraph', 'textarea'),
      F('tutorEyebrow', 'Tutor promo eyebrow'),
      F('tutorTitle', 'Tutor promo headline'),
      F('tutorLede', 'Tutor promo lede', 'textarea'),
      F('tutorCtaPrimary', 'Tutor primary button'),
      F('tutorCtaSecondary', 'Tutor secondary button'),
      F('tutorStatusPill', 'Tutor status label'),
      F('chaptersEyebrow', 'Chapters section eyebrow'),
      F('chaptersTitle', 'Chapters section headline'),
      F('chaptersLede', 'Chapters section lede', 'textarea'),
      F('chaptersCta', 'Chapters CTA link text'),
      F('educationEyebrow', 'Education section eyebrow'),
      F('educationTitle', 'Education section headline'),
      F('educationLede', 'Education section lede', 'textarea'),
      F('educationCta', 'Education CTA link text'),
      F('researchEyebrow', 'Research section eyebrow'),
      F('researchTitle', 'Research section headline'),
      F('researchLede', 'Research section lede', 'textarea'),
      F('researchCta', 'Research CTA link text'),
      F('opportunitiesEyebrow', 'Opportunities section eyebrow'),
      F('opportunitiesTitle', 'Opportunities section headline'),
      F('opportunitiesLede', 'Opportunities section lede', 'textarea'),
      F('opportunitiesCta', 'Opportunities CTA link text'),
      F('eventsEyebrow', 'Events section eyebrow'),
      F('eventsTitle', 'Events section headline'),
      F('eventsLede', 'Events section lede', 'textarea'),
      F('eventsCta', 'Events CTA link text'),
      F('partnersEyebrow', 'Partners section eyebrow'),
      F('partnersTitle', 'Partners section headline'),
      F('partnersLede', 'Partners section lede', 'textarea'),
      F('partnersCta', 'Partners CTA link text'),
      F('partnersNote', 'Partners note under logo wall', 'textarea'),
      F('communityEyebrow', 'Community section eyebrow'),
      F('communityTitle', 'Community section headline'),
      F('communityLede', 'Community section lede', 'textarea'),
      F('communityCta', 'Community CTA link text'),
      F('newsEyebrow', 'News section eyebrow'),
      F('newsTitle', 'News section headline'),
      F('newsLede', 'News section lede', 'textarea'),
      F('newsCta', 'News CTA link text'),
      F('ctaBandEyebrow', 'CTA band eyebrow'),
      F('ctaBandTitle', 'CTA band headline'),
      F('ctaBandBtn1', 'CTA band button 1'),
      F('ctaBandBtn2', 'CTA band button 2'),
      F('ctaBandBtn3', 'CTA band button 3'),
    ],
  },
  {
    'key': 'pages.about', 'title': 'Page: About', 'icon': 'doc', 'kind': 'single',
    'blurb': 'Static editorial copy on the About page. Hero text, section heads, panel copy around the people grid.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow', help='Small label above the headline, e.g. "About Quantum Africa".'),
      F('heroTitle', 'Hero headline', help='The big sentence at the top of the page.'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('heroImage', 'Hero photograph', 'image', help='Wide community photograph, 2400×1000 or larger.'),
      F('whoWeAreHead', 'Who we are — section head'),
      F('whoWeAreBody', 'Who we are — body text', 'markdown'),
      F('storyHead', 'Our story — section head'),
      F('storyBody', 'Our story — body text', 'markdown'),
      F('missionHead', 'Mission — section head'),
      F('missionBody', 'Mission — body text', 'textarea'),
      F('visionHead', 'Vision — section head'),
      F('visionBody', 'Vision — body text', 'textarea'),
      F('objectivesHead', 'Objectives — section head'),
      F('objectivesList', 'Objectives', 'tags', help='One bullet per objective.'),
      F('philosophyPanelHead', 'Philosophy panel title'),
      F('philosophyHeadline', 'Philosophy headline', help='The big line in the side panel, e.g. Educate → Research → Connect → Lead.'),
      F('philosophyBody', 'Philosophy note', 'textarea'),
      F('glancePanelHead', '"At a glance" panel title'),
      F('documentsPanelHead', 'Documents panel title'),
      F('documentsNote', 'Documents note', 'textarea', help='Annual report or strategy PDF — describe it and link it.'),
      F('peopleEyebrow', 'People section eyebrow'),
      F('peopleTitle', 'People section headline'),
      F('peopleCta', 'People CTA link text'),
    ],
  },
  {
    'key': 'pages.impact', 'title': 'Page: Impact', 'icon': 'chart', 'kind': 'single',
    'blurb': 'Static editorial copy on the Impact page — section heads, table labels, stories panel copy.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('bigNumMembersLabel', 'Big number — members label'),
      F('bigNumMembersDesc', 'Big number — members description'),
      F('bigNumChaptersLabel', 'Big number — chapters label'),
      F('bigNumChaptersDesc', 'Big number — chapters description'),
      F('bigNumProjectsLabel', 'Big number — projects label'),
      F('bigNumProjectsDesc', 'Big number — projects description'),
      F('bigNumCountriesLabel', 'Big number — countries label'),
      F('bigNumCountriesDesc', 'Big number — countries description'),
      F('bigNumEventsLabel', 'Big number — events label'),
      F('bigNumEventsDesc', 'Big number — events description'),
      F('bigNumPartnersLabel', 'Big number — partners label'),
      F('bigNumPartnersDesc', 'Big number — partners description'),
      F('detailEyebrow', 'Detail section eyebrow'),
      F('detailTitle', 'Detail section headline'),
      F('detailLede', 'Detail section lede', 'textarea'),
      F('detailTableAreaCol', 'Table — Area column head'),
      F('detailTableCountCol', 'Table — What we count column head'),
      F('detailTableFigureCol', 'Table — Figure column head'),
      F('rowCommunityArea', 'Row — Community area name'),
      F('rowCommunityCount', 'Row — Community count description'),
      F('rowCommunityFigure', 'Row — Community figure'),
      F('rowEducationArea', 'Row — Education area name'),
      F('rowEducationCount', 'Row — Education count description'),
      F('rowEducationFigure', 'Row — Education figure'),
      F('rowResearchArea', 'Row — Research area name'),
      F('rowResearchCount', 'Row — Research count description'),
      F('rowResearchFigure', 'Row — Research figure'),
      F('rowChaptersArea', 'Row — Chapters area name'),
      F('rowChaptersCount', 'Row — Chapters count description'),
      F('rowChaptersFigure', 'Row — Chapters figure'),
      F('rowEventsArea', 'Row — Events area name'),
      F('rowEventsCount', 'Row — Events count description'),
      F('rowEventsFigure', 'Row — Events figure'),
      F('rowPartnershipsArea', 'Row — Partnerships area name'),
      F('rowPartnershipsCount', 'Row — Partnerships count description'),
      F('rowPartnershipsFigure', 'Row — Partnerships figure'),
      F('storiesEyebrow', 'Stories section eyebrow'),
      F('storiesTitle', 'Stories section headline'),
      F('storiesLede', 'Stories section lede', 'textarea'),
      F('storiesCardMeta', 'Stories cards — type label'),
      F('storiesHeadlinePlaceholder', 'Stories cards — headline placeholder'),
      F('storiesWhoPlaceholder', 'Stories cards — who description placeholder'),
      F('reportPanelHead', 'Report panel title'),
      F('reportPanelBody', 'Report panel body', 'textarea'),
      F('methodologyPanelHead', 'Methodology panel title'),
      F('methodologyPanelBody', 'Methodology panel body', 'textarea'),
    ],
  },
  {
    'key': 'pages.education', 'title': 'Page: Education', 'icon': 'book', 'kind': 'single',
    'blurb': 'Static editorial copy on the Education page — hero, programme cards, archive section.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('statusWebinars', 'Status pill — webinars & workshops'),
      F('statusTutor', 'Status pill — tutor & resources'),
      F('statusUniversity', 'Status pill — university programmes'),
      F('archiveEyebrow', 'Archive section eyebrow'),
      F('archiveTitle', 'Archive section headline'),
      F('archiveLede', 'Archive section lede', 'textarea'),
      F('archiveCta', 'Archive CTA link text'),
    ],
  },
  {
    'key': 'pages.tutor', 'title': 'Page: AI Tutor', 'icon': 'chat', 'kind': 'single',
    'blurb': 'Static editorial copy on the AI Tutor page — hero, audience cards, steps, features, CTA.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('ctaPrimary', 'Primary button text'),
      F('ctaSecondary', 'Secondary button text'),
      F('statusPill', 'Status pill label'),
      F('statusNote', 'Status note'),
      F('tutorMockImage', 'Tutor mockup screenshot', 'image', help='Optional uploaded screenshot replaces the generated mock.'),
      F('audienceEyebrow', 'Audience section eyebrow'),
      F('audienceTitle', 'Audience section headline'),
      F('howEyebrow', 'How it works eyebrow'),
      F('howTitle', 'How it works headline'),
      F('howScreenshotAlt', 'How it works — screenshot alt'),
      F('featuresEyebrow', 'Features section eyebrow'),
      F('featuresTitle', 'Features section headline'),
      F('ctaBandTitle', 'CTA band headline'),
      F('ctaBandBtn1', 'CTA band button 1'),
      F('ctaBandBtn2', 'CTA band button 2'),
    ],
  },
  {
    'key': 'pages.research', 'title': 'Page: Research index', 'icon': 'atom', 'kind': 'single',
    'blurb': 'Static editorial copy on the Research landing page — hero, section heads, outputs cards, propose split.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('heroCtaJoin', 'Hero CTA — Join a project'),
      F('heroCtaResearchers', 'Hero CTA — For researchers'),
      F('activeEyebrow', 'Active projects eyebrow'),
      F('activeTitle', 'Active projects headline'),
      F('outputsEyebrow', 'Outputs section eyebrow'),
      F('outputsTitle', 'Outputs section headline'),
      F('outputsCardPubHead', 'Outputs card — Publications head'),
      F('outputsCardPubBody', 'Outputs card — Publications body', 'textarea'),
      F('outputsCardOsHead', 'Outputs card — Open source head'),
      F('outputsCardOsBodyPrefix', 'Outputs card — Open source body prefix text'),
      F('outputsCardRolesHead', 'Outputs card — Open roles head'),
      F('outputsCardRolesBody', 'Outputs card — Open roles body'),
      F('outputsCardRolesCta', 'Outputs card — Open roles CTA text'),
      F('proposeEyebrow', 'Propose section eyebrow'),
      F('proposeTitle', 'Propose section headline'),
      F('proposeLede', 'Propose section lede', 'textarea'),
      F('proposeCta', 'Propose CTA button text'),
      F('proposeImageAlt', 'Propose section image alt text'),
    ],
  },
  {
    'key': 'pages.researchDetail', 'title': 'Page: Research detail', 'icon': 'atom', 'kind': 'single',
    'blurb': 'Static editorial copy on individual research project pages — section heads, panel labels, call-to-action.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroImage', 'Project hero photo', 'image', help='Optional project photo. Generated figure is default.'),
      F('descHead', 'Description section head'),
      F('descExtendedPlaceholder', 'Extended description placeholder', 'textarea'),
      F('objectivesHead', 'Objectives section head'),
      F('joinHead', 'Join this project — head'),
      F('joinPrefix', 'Join this project — prefix sentence'),
      F('joinSkillsPlaceholder', 'Join this project — skills placeholder', 'textarea'),
      F('joinCta', 'Join this project — CTA button'),
      F('panelProjectHead', 'Side panel — Project title'),
      F('panelAreaLabel', 'Side panel — Area label'),
      F('panelStatusLabel', 'Side panel — Status label'),
      F('panelStartedLabel', 'Side panel — Started label'),
      F('panelRepoLabel', 'Side panel — Repository label'),
      F('panelPubLabel', 'Side panel — Publication label'),
      F('panelContribHead', 'Side panel — Contributors title'),
      F('moreEyebrow', 'More projects eyebrow'),
      F('moreTitle', 'More projects headline'),
      F('moreCta', 'More projects CTA link text'),
    ],
  },
  {
    'key': 'pages.chapters', 'title': 'Page: Chapters index', 'icon': 'flag', 'kind': 'single',
    'blurb': 'Static editorial copy on the Chapters landing page — hero text, start-a-chapter panel.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('allEyebrow', 'All chapters eyebrow'),
      F('allTitle', 'All chapters headline'),
      F('startPanelHead', 'Start a chapter — panel title'),
      F('startPanelBody', 'Start a chapter — panel body', 'textarea'),
      F('startPanelCta', 'Start a chapter — panel CTA button'),
      F('mapNote', 'Map note at bottom of chapter list', 'textarea'),
      F('noChapterHead', 'No chapter panel — headline'),
      F('noChapterBody', 'No chapter panel — body', 'textarea'),
      F('noChapterCta', 'No chapter panel — CTA'),
    ],
  },
  {
    'key': 'pages.chapterDetail', 'title': 'Page: Chapter detail', 'icon': 'flag', 'kind': 'single',
    'blurb': 'Static editorial copy on individual chapter pages — section heads, panel labels, call-to-action.',
    'fields': [
      F('heroImage', 'Chapter hero photo', 'image', help='Chapter team or event photo. 2400×1000.'),
      F('chapterTag', 'Chapter tag label'),
      F('joinCta', 'Join chapter — CTA button'),
      F('contactCta', 'Contact chapter — CTA button'),
      F('descPlaceholder', 'Chapter description placeholder', 'textarea', help='3–4 sentences: when formed, focus, universities involved, direction.'),
      F('leadershipEyebrow', 'Leadership section eyebrow'),
      F('leadershipTitle', 'Leadership section headline'),
      F('teamPhotoAlt', 'Team photo alt text'),
      F('teamPhoto', 'Chapter team photo', 'image', help='1600×900 team or event photo.'),
      F('activityEyebrow', 'Activity section eyebrow'),
      F('activityTitle', 'Activity section headline'),
      F('activityCta', 'Activity CTA link text'),
      F('universitiesHead', 'Universities & institutions head'),
      F('researchHead', 'Research & education in [country] head'),
      F('socialPanelHead', 'Chapter social media panel title'),
      F('socialPlaceholder', 'Social media channels placeholder', 'textarea'),
      F('networkEyebrow', 'Network section eyebrow'),
      F('networkTitle', 'Network section headline'),
      F('networkCta', 'Network CTA link text'),
    ],
  },
  {
    'key': 'pages.events', 'title': 'Page: Events index', 'icon': 'calendar', 'kind': 'single',
    'blurb': 'Static editorial copy on the Events landing page — hero, next-up feature, archive filter labels, conferences panel.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('nextMetaTag', 'Next session — meta tag prefix'),
      F('nextDatePlaceholder', 'Next session — date placeholder'),
      F('nextTimePlaceholder', 'Next session — time placeholder'),
      F('nextTitlePlaceholder', 'Next session — title placeholder'),
      F('nextAbstractPlaceholder', 'Next session — abstract placeholder', 'textarea'),
      F('nextCta', 'Next session — CTA link text'),
      F('alsoLabel', '"Also coming up" label'),
      F('alsoCta', '"Also coming up" — CTA button'),
      F('archiveEyebrow', 'Archive eyebrow'),
      F('archiveTitle', 'Archive headline'),
      F('filterWhenLabel', 'Filter — When label'),
      F('filterTypeLabel', 'Filter — Type label'),
      F('conferencesPanelHead', 'Conferences elsewhere panel title'),
      F('conferencesPanelBody', 'Conferences elsewhere panel body', 'textarea'),
      F('conferencesPanelCta', 'Conferences elsewhere panel CTA'),
    ],
  },
  {
    'key': 'pages.eventDetail', 'title': 'Page: Event detail', 'icon': 'calendar', 'kind': 'single',
    'blurb': 'Static editorial copy on individual event pages — section heads, panel labels, placeholders.',
    'fields': [
      F('heroImage', 'Event hero photo', 'image', help='Speaker portrait or event photograph. 2400×1000.'),
      F('abstractPlaceholder', 'Abstract placeholder', 'textarea'),
      F('aboutHead', 'About this session head'),
      F('aboutPlaceholder', 'Full description placeholder', 'textarea'),
      F('agendaHead', 'Agenda head'),
      F('agendaTimePlaceholder', 'Agenda time placeholder'),
      F('agendaItemPlaceholder', 'Agenda item placeholder'),
      F('speakersHead', 'Speakers head'),
      F('photosHead', 'Photos & recording head'),
      F('recordingAlt', 'Recording embed placeholder alt'),
      F('outcomesHead', 'Outcomes head'),
      F('outcomesPlaceholder', 'Outcomes placeholder', 'textarea'),
      F('resourcesHead', 'Resources head'),
      F('resourcesPlaceholder', 'Resources placeholder', 'textarea'),
      F('panelDetailsHead', 'Side panel — Details title'),
      F('panelDateLabel', 'Details — Date label'),
      F('panelTimeLabel', 'Details — Time label'),
      F('panelLocationLabel', 'Details — Location label'),
      F('panelLanguageLabel', 'Details — Language label'),
      F('panelCostLabel', 'Details — Cost label'),
      F('panelDatePlaceholder', 'Details — Date placeholder'),
      F('panelTimePlaceholder', 'Details — Time placeholder'),
      F('panelLocationPlaceholder', 'Details — Location placeholder'),
      F('panelLanguagePlaceholder', 'Details — Language placeholder'),
      F('panelCostValue', 'Details — Cost value'),
      F('ctaUpcoming', 'CTA button — upcoming event'),
      F('ctaPast', 'CTA button — past event'),
      F('ctaNote', 'CTA note under button', 'textarea'),
      F('panelOrganisersHead', 'Side panel — Organisers title'),
      F('panelOrganisersPlaceholder', 'Organisers placeholder', 'textarea'),
      F('panelPartnersHead', 'Side panel — Partners title'),
      F('moreEyebrow', 'More events eyebrow'),
      F('moreTitle', 'More events headline'),
      F('moreCta', 'More events CTA link text'),
    ],
  },
  {
    'key': 'pages.workshops', 'title': 'Page: Workshops (QML4Africa)', 'icon': 'calendar', 'kind': 'single',
    'blurb': 'Static editorial copy on the QML4Africa Workshops series page — hero, series bar, sections, gallery, CTA.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('heroCtaJoin', 'Hero CTA — join next edition'),
      F('heroCtaAll', 'Hero CTA — all events'),
      F('seriesLabel', 'Series bar — Series label'),
      F('seriesName', 'Series bar — Series name'),
      F('editionsLabel', 'Series bar — Editions delivered label'),
      F('formatLabel', 'Series bar — Format label'),
      F('formatPlaceholder', 'Series bar — Format placeholder'),
      F('participantsLabel', 'Series bar — Participants label'),
      F('participantsPlaceholder', 'Series bar — Participants count placeholder'),
      F('partnersLabel', 'Series bar — Partners label'),
      F('partnersPlaceholder', 'Series bar — Partners count placeholder'),
      F('editionBodyPlaceholder', 'Edition card — body placeholder', 'textarea'),
      F('editionDeliveredPill', 'Edition card — Delivered pill label'),
      F('editionDatesPlaceholder', 'Edition card — dates placeholder'),
      F('editionPageCta', 'Edition card — CTA link text'),
      F('plannedEditionNum', 'Planned edition — number'),
      F('plannedEditionTitle', 'Planned edition — title'),
      F('plannedEditionBody', 'Planned edition — body placeholder', 'textarea'),
      F('plannedPill', 'Planned edition — Planned pill label'),
      F('plannedCta', 'Planned edition — CTA link text'),
      F('seriesEyebrow', 'The series eyebrow'),
      F('seriesTitle', 'The series headline'),
      F('seriesLede', 'The series lede paragraph', 'textarea'),
      F('cardWhoHead', 'Info card — Who it is for head'),
      F('cardWhoBody', 'Info card — Who it is for body', 'textarea'),
      F('cardWhatHead', 'Info card — What it covers head'),
      F('cardWhatPlaceholder', 'Info card — What it covers placeholder', 'textarea'),
      F('cardLeaveHead', 'Info card — What you leave with head'),
      F('cardLeavePlaceholder', 'Info card — What you leave with placeholder', 'textarea'),
      F('organisersPanelHead', 'Panel — Organisers & partners title'),
      F('organisersPanelBody', 'Panel — Organisers & partners body', 'textarea'),
      F('materialsPanelHead', 'Panel — Recordings & materials title'),
      F('materialsPanelBody', 'Panel — Recordings & materials body', 'textarea'),
      F('galleryEyebrow', 'Gallery eyebrow'),
      F('galleryTitle', 'Gallery headline'),
      F('galleryLede', 'Gallery lede paragraph', 'textarea'),
      F('ctaBandEyebrow', 'CTA band eyebrow'),
      F('ctaBandTitle', 'CTA band headline'),
      F('ctaBandBtn1', 'CTA band button 1'),
      F('ctaBandBtn2', 'CTA band button 2'),
    ],
  },
  {
    'key': 'pages.conference', 'title': 'Page: Conference series', 'icon': 'award', 'kind': 'single',
    'blurb': 'Static editorial copy on the Conference series landing page — hero, quote, section heads, CTA.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('heroCtaLatest', 'Hero CTA — latest edition button'),
      F('heroCtaRegister', 'Hero CTA — register interest button'),
      F('blockquoteText', 'Blockquote text', 'textarea'),
      F('blockquoteCite', 'Blockquote citation'),
      F('editionsEyebrow', 'Editions timeline eyebrow'),
      F('editionsTitle', 'Editions timeline headline'),
      F('editionsLede', 'Editions timeline lede', 'textarea'),
      F('statEditionsN', 'Stat — Editions number label'),
      F('statCountriesN', 'Stat — Host countries number label'),
      F('statYearsN', 'Stat — Years number label'),
      F('statPeopleN', 'Stat — People on record number label'),
      F('latestEyebrow', 'Latest edition eyebrow'),
      F('latestPhoto', 'Latest edition photo', 'image', help='Photograph from the most recent conference.'),
      F('latestCtaPage', 'Latest edition — CTA edition page button'),
      F('latestCtaAsk', 'Latest edition — CTA ask about next button'),
      F('speakersEyebrow', 'Speakers section eyebrow'),
      F('speakersTitle', 'Speakers section headline'),
      F('speakersLede', 'Speakers section lede', 'textarea'),
      F('governanceEyebrow', 'Governance eyebrow'),
      F('governanceTitle', 'Governance headline'),
      F('governanceLede', 'Governance lede', 'textarea'),
      F('scPastLabel', 'Former steering committee label'),
      F('coversPanelHead', 'Panel — What the series covers title'),
      F('coversPanelBody', 'Panel — What the series covers body', 'textarea'),
      F('rolePanelHead', 'Panel — Quantum Africa role title'),
      F('ctaBandEyebrow', 'CTA band eyebrow'),
      F('ctaBandTitle', 'CTA band headline'),
      F('ctaBandBtn1', 'CTA band button 1'),
      F('ctaBandBtn2', 'CTA band button 2'),
    ],
  },
  {
    'key': 'pages.confEdition', 'title': 'Page: Conference edition', 'icon': 'award', 'kind': 'single',
    'blurb': 'Static editorial copy on individual conference edition pages — section heads, panel labels, placeholders.',
    'fields': [
      F('heroImage', 'Edition hero photo', 'image', help='Photograph from this conference edition. 2400×1000.'),
      F('editionTag', 'Edition tag label'),
      F('latestPill', 'Most recent pill label'),
      F('pastPill', 'Past edition pill label'),
      F('peoplePillPrefix', 'People on record — prefix'),
      F('plenaryEyebrow', 'Plenary speakers eyebrow'),
      F('plenaryLabel', 'Plenary speakers label'),
      F('keynotesEyebrow', 'Keynotes eyebrow'),
      F('keynotesTitle', 'Keynotes headline'),
      F('invitedEyebrow', 'Invited speakers eyebrow'),
      F('steeringEyebrow', 'Steering committee eyebrow'),
      F('steeringTitle', 'Steering committee headline'),
      F('ipcEyebrow', 'Programme committee eyebrow'),
      F('ipcTitle', 'Programme committee headline'),
      F('locEyebrow', 'Organising committee eyebrow'),
      F('locTitle', 'Organising committee headline'),
      F('sponsorsEyebrow', 'Sponsors eyebrow'),
      F('sponsorsTitle', 'Sponsors headline'),
      F('aboutHead', 'About this edition head'),
      F('aboutPrefix', 'About this edition — prefix sentence'),
      F('programmeHead', 'Programme head'),
      F('programmePlaceholder', 'Programme placeholder', 'textarea'),
      F('photosHead', 'Photographs head'),
      F('portraitsHead', 'Portraits and profiles head'),
      F('portraitsNote', 'Portraits and profiles note', 'textarea'),
      F('panelGlanceHead', 'Side panel — At a glance title'),
      F('panelEditionLabel', 'Panel — Edition label'),
      F('panelDatesLabel', 'Panel — Dates label'),
      F('panelCityLabel', 'Panel — City label'),
      F('panelCountryLabel', 'Panel — Country label'),
      F('panelHostLabel', 'Panel — Host label'),
      F('panelPlenaryLabel', 'Panel — Plenary label'),
      F('panelKeynotesLabel', 'Panel — Keynotes label'),
      F('panelInvitedLabel', 'Panel — Invited label'),
      F('panelIpcLabel', 'Panel — Programme cttee label'),
      F('panelLocLabel', 'Panel — Organisers label'),
      F('panelSeriesHead', 'Panel — The series title'),
      F('panelSeriesLink', 'Panel — All editions link text'),
      F('seriesEyebrow', 'Other editions eyebrow'),
      F('seriesTitle', 'Other editions headline'),
      F('seriesCta', 'Other editions CTA link text'),
    ],
  },
  {
    'key': 'pages.support', 'title': 'Page: Support', 'icon': 'heart', 'kind': 'single',
    'blurb': 'Static editorial copy on the Support / Pledge page — hero text, ways-in cards, CTA band.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('waysEyebrow', 'Ways in eyebrow'),
      F('waysTitle', 'Ways in headline'),
      F('waysLede', 'Ways in lede paragraph', 'textarea'),
      F('formHead', 'Make a pledge form title'),
      F('formIntro', 'Form intro paragraph', 'textarea'),
      F('formSubmitBtn', 'Form submit button'),
      F('formNotePlaceholder', 'Form note placeholder after button', 'textarea'),
      F('givingMoneyHead', 'Giving money panel title'),
      F('whereGoesHead', 'Where support goes panel title'),
      F('progLabel', 'Split — Programmes label'),
      F('studentLabel', 'Split — Student costs label'),
      F('opsLabel', 'Split — Operations label'),
      F('splitNote', 'Split note under breakdown', 'textarea'),
      F('partnerInsteadHead', 'Partnering instead panel title'),
      F('partnerInsteadLink', 'Partnering instead link text'),
      F('ctaBandEyebrow', 'CTA band eyebrow'),
      F('ctaBandTitle', 'CTA band headline'),
      F('ctaBandBtn1', 'CTA band button 1'),
      F('ctaBandBtn2', 'CTA band button 2'),
    ],
  },
  {
    'key': 'pages.opportunities', 'title': 'Page: Opportunities', 'icon': 'star', 'kind': 'single',
    'blurb': 'Static editorial copy on the Opportunities page — hero, Africa panel, filter labels, info panels.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('feedLoading', 'Feed loading note'),
      F('africaBadge', 'Africa badge label'),
      F('africaHead', 'Based in Africa — panel title'),
      F('africaBody', 'Based in Africa — panel body', 'textarea'),
      F('africaEmptyHead', 'Empty state — headline'),
      F('africaEmptyBody', 'Empty state — body', 'textarea'),
      F('africaClosedNote', 'All-closed listings note', 'textarea'),
      F('allEyebrow', 'All listings eyebrow'),
      F('allTitle', 'All listings headline'),
      F('allLede', 'All listings lede', 'textarea'),
      F('filterSearchLabel', 'Filter — Search label'),
      F('filterSearchPlaceholder', 'Filter — Search placeholder'),
      F('filterRegionLabel', 'Filter — Region label'),
      F('filterTypeLabel', 'Filter — Type label'),
      F('filterStatusLabel', 'Filter — Status label'),
      F('filterSourceLabel', 'Filter — Source label'),
      F('filterSortLabel', 'Filter — Sort label'),
      F('clearFiltersBtn', 'Clear filters button label'),
      F('resultLabel', 'Results label suffix'),
      F('whereFromHead', 'Where this comes from panel title'),
      F('whereFromBody', 'Where this comes from body prefix', 'textarea'),
      F('submitHead', 'Submit an opportunity panel title'),
      F('submitBody', 'Submit an opportunity body', 'textarea'),
      F('submitCta', 'Submit an opportunity CTA'),
      F('wwEyebrow', 'Worldwide calendar eyebrow'),
      F('wwTitle', 'Worldwide calendar headline'),
      F('wwLede', 'Worldwide calendar lede', 'textarea'),
      F('wwLoading', 'Worldwide — loading note'),
      F('wwFilterSearchLabel', 'WW filter — Search label'),
      F('wwFilterSearchPlaceholder', 'WW filter — Search placeholder'),
      F('wwFilterRegionLabel', 'WW filter — Region label'),
      F('wwFilterTypeLabel', 'WW filter — Type label'),
      F('wwFilterWhenLabel', 'WW filter — When label'),
      F('wwFilterSortLabel', 'WW filter — Sort label'),
      F('wwClearBtn', 'WW — Clear filters button'),
      F('wwAfricaPanelHead', 'WW — running in Africa panel title'),
      F('wwAfricaPanelBody', 'WW — running in Africa panel body', 'textarea'),
      F('wwAfricaPanelCta', 'WW — running in Africa panel CTA'),
    ],
  },
  {
    'key': 'pages.people', 'title': 'Page: People / Team', 'icon': 'user', 'kind': 'single',
    'blurb': 'Static editorial copy on the Team page — hero text, wider community section, CTA band.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('widerEyebrow', 'Wider community eyebrow'),
      F('widerTitle', 'Wider community headline'),
      F('widerLede', 'Wider community lede', 'textarea'),
      F('widerMembersN', 'Wider — Members number label'),
      F('widerChaptersN', 'Wider — Chapters number label'),
      F('widerCountriesN', 'Wider — Countries reached number label'),
      F('widerMembersDesc', 'Wider — Members description'),
      F('widerChaptersDesc', 'Wider — Chapters description'),
      F('widerCountriesDesc', 'Wider — Countries reached description'),
      F('directoryPanelHead', 'Member directory panel title'),
      F('directoryPanelBody', 'Member directory panel body', 'textarea'),
      F('ctaBandEyebrow', 'CTA band eyebrow'),
      F('ctaBandTitle', 'CTA band headline'),
      F('ctaBandBtn1', 'CTA band button 1'),
      F('ctaBandBtn2', 'CTA band button 2'),
    ],
  },
  {
    'key': 'pages.partners', 'title': 'Page: Partners', 'icon': 'link', 'kind': 'single',
    'blurb': 'Static editorial copy on the Partners page — hero, section heads, become-a-partner cards, CTA band.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('heroCta', 'Hero CTA button'),
      F('cardNamePlaceholder', 'Partner card — name placeholder'),
      F('cardCollabPlaceholder', 'Partner card — collaboration line placeholder', 'textarea'),
      F('becomeEyebrow', 'Become a partner eyebrow'),
      F('becomeTitle', 'Become a partner headline'),
      F('ctaBandTitle', 'CTA band headline'),
      F('ctaBandBtn1', 'CTA band button 1'),
      F('ctaBandBtn2', 'CTA band button 2'),
    ],
  },
  {
    'key': 'pages.universities', 'title': 'Page: Universities', 'icon': 'book', 'kind': 'single',
    'blurb': 'Static editorial copy on the For Universities page — hero, why-partner cards, how-it-starts steps, CTA.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('heroCtaStart', 'Hero CTA — start partnership button'),
      F('heroCtaProgrammes', 'Hero CTA — see programmes button'),
      F('heroImage', 'Hero photograph', 'image', help='Workshop at a university campus. 2400×1000.'),
      F('whyEyebrow', 'Why partner eyebrow'),
      F('whyTitle', 'Why partner headline'),
      F('whyLede', 'Why partner lede', 'textarea'),
      F('howEyebrow', 'How it starts eyebrow'),
      F('howTitle', 'How it starts headline'),
      F('ctaBandTitle', 'CTA band headline'),
      F('ctaBandBtn', 'CTA band button'),
    ],
  },
  {
    'key': 'pages.students', 'title': 'Page: For Students', 'icon': 'user', 'kind': 'single',
    'blurb': 'Static editorial copy on the For Students page — hero, journey chooser, reality check, voices, CTA.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('chooserGoLabel', 'Chooser card — Go suffix'),
      F('realityEyebrow', 'Reality check eyebrow'),
      F('realityTitle', 'Reality check headline'),
      F('realityLede', 'Reality check lede', 'textarea'),
      F('voicesEyebrow', 'Voices eyebrow'),
      F('voicesTitle', 'Voices headline'),
      F('voicesCta', 'Voices CTA link text'),
      F('voicesQuotePlaceholder', 'Voices — quote placeholder'),
      F('voicesWhoPlaceholder', 'Voices — who placeholder'),
      F('ctaBandEyebrow', 'CTA band eyebrow'),
      F('ctaBandTitle', 'CTA band headline'),
      F('ctaBandBtn1', 'CTA band button 1'),
      F('ctaBandBtn2', 'CTA band button 2'),
    ],
  },
  {
    'key': 'pages.researchers', 'title': 'Page: For Researchers', 'icon': 'atom', 'kind': 'single',
    'blurb': 'Static editorial copy on the For Researchers page — hero text, section heads, pillar cards, CTA.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('projectsEyebrow', 'Projects eyebrow'),
      F('projectsTitle', 'Projects headline'),
      F('projectsCta', 'Projects CTA link text'),
      F('ctaBandTitle', 'CTA band headline'),
      F('ctaBandBtn1', 'CTA band button 1'),
      F('ctaBandBtn2', 'CTA band button 2'),
    ],
  },
  {
    'key': 'pages.news', 'title': 'Page: News index', 'icon': 'news', 'kind': 'single',
    'blurb': 'Static editorial copy on the News landing page — hero, archive filter labels, newsletter section.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('archiveEyebrow', 'Archive eyebrow'),
      F('archiveTitle', 'Archive headline'),
      F('filterTypeLabel', 'Filter — Type label'),
      F('filterChapterLabel', 'Filter — Chapter label'),
      F('resultLabel', 'Results label suffix'),
      F('newsletterEyebrow', 'Newsletter eyebrow'),
      F('newsletterTitle', 'Newsletter headline'),
      F('newsletterLede', 'Newsletter lede', 'textarea'),
      F('newsletterFormHead', 'Newsletter form — Subscribe title'),
      F('newsletterNameLabel', 'Newsletter form — Name label'),
      F('newsletterNamePlaceholder', 'Newsletter form — Name placeholder'),
      F('newsletterEmailLabel', 'Newsletter form — Email label'),
      F('newsletterEmailPlaceholder', 'Newsletter form — Email placeholder'),
      F('newsletterCountryLabel', 'Newsletter form — Country label'),
      F('newsletterSubmitBtn', 'Newsletter form — submit button'),
      F('newsletterPrivacyNote', 'Newsletter form — privacy note', 'textarea'),
    ],
  },
  {
    'key': 'pages.article', 'title': 'Page: Article detail', 'icon': 'news', 'kind': 'single',
    'blurb': 'Static editorial copy on individual article pages — placeholders, section heads, author panel.',
    'fields': [
      F('heroImage', 'Article hero image', 'image', help='Article header photo. 2400×1000.'),
      F('metaTypePlaceholder', 'Meta — Type placeholder'),
      F('metaDatePlaceholder', 'Meta — Date placeholder'),
      F('metaReadPlaceholder', 'Meta — Read time placeholder'),
      F('headlinePlaceholder', 'Article headline placeholder'),
      F('standfirstPlaceholder', 'Standfirst placeholder', 'textarea'),
      F('bodyPlaceholder1', 'Body — first paragraph placeholder', 'markdown'),
      F('bodyPlaceholder2', 'Body — continued placeholder', 'markdown'),
      F('subheadPlaceholder', 'Subheading placeholder'),
      F('bodyPlaceholder3', 'Body — after subhead placeholder', 'markdown'),
      F('authorPanelHead', 'Author panel title'),
      F('authorNamePlaceholder', 'Author — name placeholder'),
      F('authorRolePlaceholder', 'Author — role placeholder'),
      F('authorChapterPlaceholder', 'Author — chapter placeholder'),
      F('moreEyebrow', 'Related articles eyebrow'),
      F('moreTitle', 'Related articles headline'),
      F('moreCta', 'Related articles CTA link text'),
    ],
  },
  {
    'key': 'pages.join', 'title': 'Page: Join', 'icon': 'user', 'kind': 'single',
    'blurb': 'Static editorial copy on the Join page — hero, form labels, panels, what-you-get list.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('formHead', 'Membership form title'),
      F('formIntro', 'Form intro paragraph', 'textarea'),
      F('formNameLabel', 'Form — Full name label'),
      F('formNamePlaceholder', 'Form — Full name placeholder'),
      F('formEmailLabel', 'Form — Email label'),
      F('formEmailPlaceholder', 'Form — Email placeholder'),
      F('formCountryLabel', 'Form — Country label'),
      F('formCountryPlaceholder', 'Form — Country placeholder'),
      F('formInstitutionLabel', 'Form — Institution label'),
      F('formInstitutionPlaceholder', 'Form — Institution placeholder'),
      F('formRoleLabel', 'Form — I am a… label'),
      F('formLookingLabel', 'Form — What are you looking for? label'),
      F('formLookingPlaceholder', 'Form — looking-for placeholder', 'textarea'),
      F('formSubmitBtn', 'Form submit button text'),
      F('getHead', 'What you get panel title'),
      F('getItem1', 'What you get — item 1'),
      F('getItem2', 'What you get — item 2'),
      F('getItem3', 'What you get — item 3'),
      F('getItem4', 'What you get — item 4'),
      F('getItem5', 'What you get — item 5'),
      F('otherHead', 'Other ways in panel title'),
      F('otherLink1', 'Other ways in — link 1 text'),
      F('otherLink2', 'Other ways in — link 2 text'),
      F('otherLink3', 'Other ways in — link 3 text'),
    ],
  },
  {
    'key': 'pages.contact', 'title': 'Page: Contact', 'icon': 'email', 'kind': 'single',
    'blurb': 'Static editorial copy on the Contact page — hero text, form labels, direct contact panel.',
    'fields': [
      F('heroEyebrow', 'Hero eyebrow'),
      F('heroTitle', 'Hero headline'),
      F('heroLede', 'Hero lede paragraph', 'textarea'),
      F('formNameLabel', 'Form — Name label'),
      F('formNamePlaceholder', 'Form — Name placeholder'),
      F('formEmailLabel', 'Form — Email label'),
      F('formEmailPlaceholder', 'Form — Email placeholder'),
      F('formReasonLabel', 'Form — Reason label'),
      F('reasonPartnership', 'Reason option — Partnership'),
      F('reasonUniversity', 'Reason option — University collaboration'),
      F('reasonMedia', 'Reason option — Media'),
      F('reasonSpeaking', 'Reason option — Speaking request'),
      F('reasonOpportunity', 'Reason option — Submit an opportunity'),
      F('reasonOther', 'Reason option — Other'),
      F('formMessageLabel', 'Form — Message label'),
      F('formMessagePlaceholder', 'Form — Message placeholder'),
      F('formSubmitBtn', 'Form submit button text'),
      F('directHead', 'Direct contact panel title'),
      F('directEmailLabel', 'Direct — Email label'),
      F('directEmailValue', 'Direct — Email address'),
      F('directLinkedinLabel', 'Direct — LinkedIn label'),
      F('directLinkedinValue', 'Direct — LinkedIn page name'),
      F('directBasedLabel', 'Direct — Based in label'),
      F('directBasedValue', 'Direct — Based in value'),
    ],
  },
]

SECTION_BY_KEY = {s['key']: s for s in SECTIONS}


def blank_doc():
    """An empty document with the right shape — collections empty, singles {}."""
    return {s['key']: ([] if s['kind'] == 'collection' else {}) for s in SECTIONS}


def _clean_value(field, value):
    t = field['type']
    if value is None:
        return None
    if t == 'number':
        if value == '' or value is None:
            return None
        try:
            return int(value)
        except (TypeError, ValueError):
            try:
                return float(value)
            except (TypeError, ValueError):
                return None
    if t == 'tags':
        if isinstance(value, str):
            return [v.strip() for v in value.split(',') if v.strip()]
        if isinstance(value, list):
            return [str(v).strip() for v in value if str(v).strip()]
        return []
    if t == 'list':
        if not isinstance(value, list):
            return []
        return [_clean_group(field.get('fields', []), row) for row in value
                if isinstance(row, dict)]
    return str(value)


def _clean_group(fields, data):
    out = {}
    for f in fields:
        if f['key'] in data:
            v = _clean_value(f, data[f['key']])
            if v not in (None, '', []):
                out[f['key']] = v
    # ids let the site keep a stable identity across renames
    if 'id' in data and data['id']:
        out['id'] = str(data['id'])
    return out


def clean(doc: dict) -> dict:
    """Keep only known sections and fields, coerce types, drop empties.

    Anything the schema does not describe is discarded — the admin panel cannot
    smuggle arbitrary keys into what the website renders.
    """
    if not isinstance(doc, dict):
        return blank_doc()
    out = blank_doc()
    for section in SECTIONS:
        k, incoming = section['key'], doc.get(section['key'])
        if incoming is None:
            continue
        if section['kind'] == 'collection':
            if isinstance(incoming, list):
                out[k] = [_clean_group(section['fields'], row) for row in incoming
                          if isinstance(row, dict)]
                out[k] = [r for r in out[k] if r]
        else:
            if isinstance(incoming, dict):
                out[k] = _clean_group(section['fields'], incoming)
    return out


def public_schema():
    """The schema as the admin panel consumes it."""
    return {'sections': SECTIONS}
